APP:
  NAME: consumer-blueprint
  DEBUG: true
  WORKER: 1

KAFKA:
  BROKER: 127.0.0.1:9092
  WORKERS: 1
  TOPIC: consumer-blueprint
  TOPIC_RETRY:
  TOPIC_DLQ:

  USERNAME:
  PASSWORD:
  SECURITY_PROTOCOL: SASL_PLAINTEXT
  SASL_MECHANISMS: PLAIN

LOG:
  LEVEL: debug
  FILE_PATH: tmp/log
